id: https://w3id.org/mim/core/project
name: mim_core_project
title: MIM project
description: JERM-aligned project grouping investigations.
version: 1.0.0
license: https://creativecommons.org/licenses/by/4.0/
imports:
- linkml:types
- common
- institution
- person
- investigation
- funding
- attribution
default_prefix: mim
default_range: string
prefixes:
  linkml: https://w3id.org/linkml/
  mim: https://w3id.org/mim/
  jerm: http://jermontology.org/ontology/JERMOntology#
  sh: http://www.w3.org/ns/shacl#
  prov: http://www.w3.org/ns/prov#
  orcid: https://orcid.org/
created_by: orcid:0000-0002-4904-3269
annotations:
  created_by_name: Tooba Abbassi-Daloii
  created_by_affiliation: Amsterdam UMC; ACDC
  schema_status: draft
  namespace_status: provisional
  ecosystem_name: Multiomics and Imaging Metadata (MIM)
  semantic_basis: JERM
  module_name: project
  profile: core
classes:
  MIMProject:
    class_uri: jerm:Project
    mixins:
    - MIMIdentifiedMixin
    - MIMNamedMixin
    - MIMDescribedMixin
    extra_slots:
      allowed: true
    attributes:
      institutions:
        range: MIMInstitution
        slot_uri: mim:MIMProject_institutions
        multivalued: true
      members:
        range: MIMPerson
        slot_uri: mim:MIMProject_members
        multivalued: true
      investigations:
        range: MIMInvestigation
        slot_uri: mim:MIMProject_investigations
        multivalued: true
      funding:
        range: MIMFunding
        slot_uri: mim:MIMProject_funding
        multivalued: true
      attribution:
        range: MIMAttribution
        slot_uri: mim:MIMProject_attribution
        inlined: true
